# Sowing Success: How Machine Learning Helps Farmers Select the Best Crops

Measuring essential soil metrics such as nitrogen, phosphorous, potassium levels, and pH value is an important aspect of assessing soil condition. However, it can be an expensive and time-consuming process, which can cause farmers to prioritize which metrics to measure based on their budget constraints.

Farmers have various options when it comes to deciding which crop to plant each season. Their primary objective is to maximize the yield of their crops, taking into account different factors. One crucial factor that affects crop growth is the condition of the soil in the field, which can be assessed by measuring basic elements such as nitrogen and potassium levels. Each crop has an ideal soil condition that ensures optimal growth and maximum yield.

A farmer reached out to you as a machine learning expert for assistance in selecting the best crop for his field. They've provided you with a dataset called `soil_measures.csv`, which contains:

- `"N"`: Nitrogen content ratio in the soil
- `"P"`: Phosphorous content ratio in the soil
- `"K"`: Potassium content ratio in the soil
- `"pH"` value of the soil
- `"crop"`: categorical values that contain various crops (target variable).

Each row in this dataset represents various measures of the soil in a particular field. Based on these measurements, the crop specified in the `"crop"` column is the optimal choice for that field.  

In this project, you will apply machine learning to build a multi-class classification model to predict the type of `"crop"`, while using techniques to avoid multicollinearity, which is a concept where two or more features are highly correlated.

# Import Libraries

In [124]:
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import plotly.express as px
from sklearn.preprocessing import MinMaxScaler

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn import svm


from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.model_selection import train_test_split 

from sklearn.metrics import \
     classification_report, confusion_matrix,\
     accuracy_score, precision_score, recall_score, f1_score,roc_auc_score

# Load the Dataset and make EDA

- Print the head, tail, describe, info, shape.

In [125]:
df = pd.read_csv('./soil_measures.csv')
df

N   P   K        ph    crop
0      90  42  43  6.502985    rice
1      85  58  41  7.038096    rice
2      60  55  44  7.840207    rice
3      74  35  40  6.980401    rice
4      78  42  42  7.628473    rice
...   ...  ..  ..       ...     ...
2195  107  34  32  6.780064  coffee
2196   99  15  27  6.086922  coffee
2197  118  33  30  6.362608  coffee
2198  117  32  34  6.758793  coffee
2199  104  18  30  6.779833  coffee

[2200 rows x 5 columns]

In [126]:
df.head()

N   P   K        ph  crop
0  90  42  43  6.502985  rice
1  85  58  41  7.038096  rice
2  60  55  44  7.840207  rice
3  74  35  40  6.980401  rice
4  78  42  42  7.628473  rice

In [127]:
df.tail()

N   P   K        ph    crop
2195  107  34  32  6.780064  coffee
2196   99  15  27  6.086922  coffee
2197  118  33  30  6.362608  coffee
2198  117  32  34  6.758793  coffee
2199  104  18  30  6.779833  coffee

In [128]:
df.describe()

N            P            K           ph
count  2200.000000  2200.000000  2200.000000  2200.000000
mean     50.551818    53.362727    48.149091     6.469480
std      36.917334    32.985883    50.647931     0.773938
min       0.000000     5.000000     5.000000     3.504752
25%      21.000000    28.000000    20.000000     5.971693
50%      37.000000    51.000000    32.000000     6.425045
75%      84.250000    68.000000    49.000000     6.923643
max     140.000000   145.000000   205.000000     9.935091

In [129]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   N       2200 non-null   int64  
 1   P       2200 non-null   int64  
 2   K       2200 non-null   int64  
 3   ph      2200 non-null   float64
 4   crop    2200 non-null   object 
dtypes: float64(1), int64(3), object(1)
memory usage: 86.1+ KB


In [130]:
df.shape

(2200, 5)

In [131]:
# Import label encoder 
from sklearn import preprocessing 

# label_encoder object knows 
# how to understand word labels. 
label_encoder = preprocessing.LabelEncoder() 

df['crop']= label_encoder.fit_transform(df['crop']) 

df['crop'].unique() 


array([20, 11,  3,  9, 18, 13, 14,  2, 10, 19,  1, 12,  7, 21, 15,  0, 16,
       17,  4,  6,  8,  5])

# Check the number of classes in the target label

In [132]:
len(df['crop'].unique())

22

# Check is there missing data

In [133]:
df.isna().sum()

N       0
P       0
K       0
ph      0
crop    0
dtype: int64

# Train test split

- Test size is 20%

In [134]:
X = df.drop('crop',axis=1)
y = df['crop']

X_train, X_test, y_train, y_test = train_test_split(X,y , 
                                   random_state=42,  
                                   test_size=0.20) 

# Train a multiclass logistic regression model, make predictions and evaluate the model

- Accuracy, f1-score, precision, recall, confusion matrix, and classification report.

In [135]:


logmodel = LogisticRegression()
logmodel.fit(X_train,y_train)


print(logmodel.intercept_)
print(logmodel.coef_)




y_pred = logmodel.predict(X_test)
print(y_pred)
print(f'The confusion matrix :-\n{confusion_matrix(y_test, y_pred)}')
report = classification_report(y_test, y_pred)
print("Classification Report:\n", report)
print(f'The accuracy of the model : {accuracy_score(y_test, y_pred)}')

print(f'The precision of the model : {precision_score(y_test, y_pred,average="micro")}')
print(f'The recall of the model : {recall_score(y_test, y_pred,average="micro")}')
print(f'The f1 score of the model : {f1_score(y_test, y_pred,average="micro")}')

[-0.09730025 -0.10551362 -0.04249028 -0.0953834   0.12154554 -0.00890128
 -0.03412684 -0.09828087 -0.01326145 -0.02357081 -0.02989098  0.00585215
  0.1803264   0.03742027  0.05529746 -0.03026183  0.25373055 -0.06021209
 -0.02799915  0.04658463 -0.00702226 -0.02654187]
[[-0.45074626 -0.08168061  0.67312476 -0.63227112]
 [ 0.11452163  0.22705084 -0.13944517 -0.77617328]
 [ 0.06581212  0.41554151 -0.59441531 -0.04405872]
 [-0.21674382 -0.11687259  0.63280274 -0.32812015]
 [-0.20375741 -0.27717093  0.61577057  0.57255633]
 [ 0.45346548 -0.44035931 -0.33863857 -0.0387292 ]
 [ 0.47228032 -0.02450384 -1.00416644 -0.16587726]
 [-0.43029537 -0.10789148  0.68745641 -0.58299702]
 [ 0.13203101 -0.00232306  0.02348922  0.06308798]
 [-0.07924473  0.46862048 -0.40423984 -0.50248867]
 [-0.08357505  0.44815745 -0.5241998   0.11496981]
 [ 0.2664612   0.26521605 -0.73619467 -0.07010469]
 [-0.23618479 -0.13752061  0.52193581  0.705445  ]
 [-0.06112063  0.26053642 -0.13214151  0.43543835]
 [-0.07319657  0.

# Train a SVM model, make predictions and evaluate the model

- Accuracy, f1-score, precision, recall, confusion matrix, and classification report.

In [136]:
model = svm.SVC(kernel='rbf',random_state=32)

model.fit(X_train,y_train)

y_pred=model.predict(X_test)
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
print("Classification Report:\n", report)


print(f'The confusion matrix :-\n{confusion_matrix(y_test, y_pred)}')

print(f'The accuracy of the model : {accuracy_score(y_test, y_pred)}')

print(f'The precision of the model : {precision_score(y_test, y_pred,average="micro")}')
print(f'The recall of the model : {recall_score(y_test, y_pred,average="micro")}')
print(f'The f1 score of the model : {f1_score(y_test, y_pred,average="micro")}')




The classification report :-
[[ 1  0  0  0  0  0  0 22  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 11  0  0  0  0  0  0  0  9  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 18  0  0  0  0  0  0  0  8  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0 15  1  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 14  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0 22  0]
 [ 0  0  3  0  0  0  0  0  0  0 16  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  1  9  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  4  0  0  0  0 16  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0  0  0 13  0  1  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0  3  0  0  0 20  0  0  0  0  0  0  0]
 [ 0 

# Train a Decision tree model, make predictions and evaluate the model

- Accuracy, f1-score, precision, recall, confusion matrix, and classification report.

In [144]:
from matplotlib.pyplot import xticks
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(random_state = 1912, criterion='entropy')
tree.fit(X_train, y_train)

y_pred = tree.predict(X_test)


report = classification_report(y_test, y_pred)
print("Classification Report:\n", report)


print(f'The confusion matrix :-\n{confusion_matrix(y_test, y_pred)}')

print(f'The accuracy of the model : {accuracy_score(y_test, y_pred)}')

Classification Report:
               precision    recall  f1-score   support

           0       0.62      0.57      0.59        23
           1       1.00      1.00      1.00        21
           2       0.89      0.80      0.84        20
           3       1.00      1.00      1.00        26
           4       0.83      0.89      0.86        27
           5       0.89      0.94      0.91        17
           6       0.89      1.00      0.94        17
           7       0.38      0.43      0.40        14
           8       0.50      0.48      0.49        23
           9       0.74      0.70      0.72        20
          10       0.19      0.36      0.25        11
          11       1.00      0.95      0.98        21
          12       0.78      0.74      0.76        19
          13       0.82      0.75      0.78        24
          14       0.93      0.74      0.82        19
          15       0.57      0.47      0.52        17
          16       1.00      1.00      1.00        14
   

# Train a RF model, make predictions and evaluate the model

- Accuracy, f1-score, precision, recall, confusion matrix, and classification report.

In [148]:
from sklearn.ensemble import RandomForestClassifier

forest = RandomForestClassifier(n_estimators = 100,
                                criterion = 'entropy',
                                max_depth = 6,
                                min_samples_leaf = 10,
                                min_samples_split = 78,
                                bootstrap = True,
                                oob_score = True,
                                random_state = 1912)

forest.fit(X_train, y_train)

prediction = forest.predict(X_test)

print("Classification Report:\n", report)


print(f'The confusion matrix :-\n{confusion_matrix(y_test, y_pred)}')

print(f'The accuracy of the model : {accuracy_score(y_test, y_pred)}')

print(f'The precision of the model : {precision_score(y_test, y_pred,average="micro")}')
print(f'The recall of the model : {recall_score(y_test, y_pred,average="micro")}')
print(f'The f1 score of the model : {f1_score(y_test, y_pred,average="micro")}')

Classification Report:
               precision    recall  f1-score   support

           0       0.62      0.57      0.59        23
           1       1.00      1.00      1.00        21
           2       0.89      0.80      0.84        20
           3       1.00      1.00      1.00        26
           4       0.83      0.89      0.86        27
           5       0.89      0.94      0.91        17
           6       0.89      1.00      0.94        17
           7       0.38      0.43      0.40        14
           8       0.50      0.48      0.49        23
           9       0.74      0.70      0.72        20
          10       0.19      0.36      0.25        11
          11       1.00      0.95      0.98        21
          12       0.78      0.74      0.76        19
          13       0.82      0.75      0.78        24
          14       0.93      0.74      0.82        19
          15       0.57      0.47      0.52        17
          16       1.00      1.00      1.00        14
   

# Train a default KNN model, make predictions and evaluate the model

- Accuracy, f1-score, precision, recall, confusion matrix, and classification report.

In [137]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=1)

knn.fit(X_train, y_train)

y_pred=knn.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
print("Classification Report:\n", report)

print(f'The confusion matrix :-\n{confusion_matrix(y_test, y_pred)}')

print(f'The accuracy of the model : {accuracy_score(y_test, y_pred)}')

print(f'The precision of the model : {precision_score(y_test, y_pred,average="micro")}')
print(f'The recall of the model : {recall_score(y_test, y_pred,average="micro")}')
print(f'The f1 score of the model : {f1_score(y_test, y_pred,average="micro")}')


Classification Report:
               precision    recall  f1-score   support

           0       0.56      0.39      0.46        23
           1       1.00      1.00      1.00        21
           2       0.67      0.60      0.63        20
           3       1.00      1.00      1.00        26
           4       0.64      0.67      0.65        27
           5       0.83      0.88      0.86        17
           6       0.84      0.94      0.89        17
           7       0.33      0.50      0.40        14
           8       0.68      0.65      0.67        23
           9       0.18      0.15      0.16        20
          10       0.16      0.27      0.20        11
          11       0.95      0.90      0.93        21
          12       0.50      0.53      0.51        19
          13       0.35      0.25      0.29        24
          14       0.28      0.37      0.32        19
          15       0.45      0.59      0.51        17
          16       1.00      1.00      1.00        14
   

# Try different values of K in the KNN model and select the best one.

- Based on the accuracy.

In [149]:
from sklearn.model_selection import GridSearchCV

knn = KNeighborsClassifier()

param_grid = dict(n_neighbors = list(range(1,100)))

grid = GridSearchCV(knn, param_grid, cv = 5, scoring = 'accuracy')
grid.fit(X_train,y_train)

print (grid.best_score_)
print (grid.best_params_)
print (grid.best_estimator_)

0.65625
{'n_neighbors': 4}
KNeighborsClassifier(n_neighbors=4)
