# Sowing Success: How Machine Learning Helps Farmers Select the Best Crops

Measuring essential soil metrics such as nitrogen, phosphorous, potassium levels, and pH value is an important aspect of assessing soil condition. However, it can be an expensive and time-consuming process, which can cause farmers to prioritize which metrics to measure based on their budget constraints.

Farmers have various options when it comes to deciding which crop to plant each season. Their primary objective is to maximize the yield of their crops, taking into account different factors. One crucial factor that affects crop growth is the condition of the soil in the field, which can be assessed by measuring basic elements such as nitrogen and potassium levels. Each crop has an ideal soil condition that ensures optimal growth and maximum yield.

A farmer reached out to you as a machine learning expert for assistance in selecting the best crop for his field. They've provided you with a dataset called `soil_measures.csv`, which contains:

- `"N"`: Nitrogen content ratio in the soil
- `"P"`: Phosphorous content ratio in the soil
- `"K"`: Potassium content ratio in the soil
- `"pH"` value of the soil
- `"crop"`: categorical values that contain various crops (target variable).

Each row in this dataset represents various measures of the soil in a particular field. Based on these measurements, the crop specified in the `"crop"` column is the optimal choice for that field.  

In this project, you will apply machine learning to build a multi-class classification model to predict the type of `"crop"`, while using techniques to avoid multicollinearity, which is a concept where two or more features are highly correlated.

# Import Libraries

In [85]:
import sys
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns

# Load the Dataset and make EDA

- Print the head, tail, describe, info, shape.

In [86]:
df = pd.read_csv('soil_measures.csv')

In [87]:
df.head()

N   P   K        ph  crop
0  90  42  43  6.502985  rice
1  85  58  41  7.038096  rice
2  60  55  44  7.840207  rice
3  74  35  40  6.980401  rice
4  78  42  42  7.628473  rice

In [88]:
df.tail()

N   P   K        ph    crop
2195  107  34  32  6.780064  coffee
2196   99  15  27  6.086922  coffee
2197  118  33  30  6.362608  coffee
2198  117  32  34  6.758793  coffee
2199  104  18  30  6.779833  coffee

In [89]:
df.describe()

N            P            K           ph
count  2200.000000  2200.000000  2200.000000  2200.000000
mean     50.551818    53.362727    48.149091     6.469480
std      36.917334    32.985883    50.647931     0.773938
min       0.000000     5.000000     5.000000     3.504752
25%      21.000000    28.000000    20.000000     5.971693
50%      37.000000    51.000000    32.000000     6.425045
75%      84.250000    68.000000    49.000000     6.923643
max     140.000000   145.000000   205.000000     9.935091

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   N       2200 non-null   int64  
 1   P       2200 non-null   int64  
 2   K       2200 non-null   int64  
 3   ph      2200 non-null   float64
 4   crop    2200 non-null   object 
dtypes: float64(1), int64(3), object(1)
memory usage: 86.1+ KB


In [91]:
df.shape

(2200, 5)

# Check the number of classes in the target label

In [92]:
print(df['crop'].value_counts())
df['crop'].unique()

crop
rice           100
maize          100
jute           100
cotton         100
coconut        100
papaya         100
orange         100
apple          100
muskmelon      100
watermelon     100
grapes         100
mango          100
banana         100
pomegranate    100
lentil         100
blackgram      100
mungbean       100
mothbeans      100
pigeonpeas     100
kidneybeans    100
chickpea       100
coffee         100
Name: count, dtype: int64


array(['rice', 'maize', 'chickpea', 'kidneybeans', 'pigeonpeas',
       'mothbeans', 'mungbean', 'blackgram', 'lentil', 'pomegranate',
       'banana', 'mango', 'grapes', 'watermelon', 'muskmelon', 'apple',
       'orange', 'papaya', 'coconut', 'cotton', 'jute', 'coffee'],
      dtype=object)

# Check is there missing data

In [93]:
df.isna().sum()

N       0
P       0
K       0
ph      0
crop    0
dtype: int64

# Train test split

- Test size is 20%

In [94]:
from sklearn.model_selection import train_test_split

In [95]:
x = df.loc[:,['N', 'P', 'K', 'ph']]
y = df.loc[:,['crop']]
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
print('test is :', y_test.count(),'train is :', y_train.count())

test is : crop    440
dtype: int64 train is : crop    1760
dtype: int64


# Train a multiclass logistic regression model, make predictions and evaluate the model

- Accuracy, f1-score, precision, recall, confusion matrix, and classification report.

In [96]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import Lasso, Ridge, ElasticNet
from sklearn.metrics import accuracy_score,confusion_matrix, recall_score, precision_score, f1_score, roc_auc_score
from sklearn.metrics import classification_report

In [97]:
logreg = LogisticRegression()
logreg.fit(x_train,y_train)

/Users/abdullah/anaconda3/envs/Data_Analysis/lib/python3.11/site-packages/sklearn/utils/validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/abdullah/anaconda3/envs/Data_Analysis/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [98]:
y_pred = logreg.predict(x_test)

In [99]:
acc = accuracy_score(y_test, y_pred)
print('accuracy_score is : ', acc)

f1 = f1_score(y_test, y_pred, average='weighted')
print('f1_score is : ', f1)

prec = precision_score(y_test, y_pred, average='weighted')
print('precision_score is : ', prec)

recall = recall_score(y_test, y_pred, average='weighted')
print('recall_score is : ', recall)

cm = confusion_matrix(y_test, y_pred)
print('confusion_matrix is : ', cm)

accuracy_score is :  0.5681818181818182
f1_score is :  0.5454206655375167
precision_score is :  0.5658736017236404
recall_score is :  0.5681818181818182
confusion_matrix is :  [[ 4  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 10  0  0  0  0  0  0  1  7  0  0  1  1  0  0  0  0  0  0  0]
 [ 0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0  0  0 10  0  0  0  0  0  0 11  0  1]
 [ 0  0  0  0  0 16  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  0  0  0  0  0  0 11  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  1  0  0  8  0  0  0  0  0  0  0  0  2  0  0 10  0]
 [ 0  0  3  0  0  0  0  0  0  5  4  0  0  0  1  0  0  0  7  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  1  6  0  0  1  1  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  5  0  1  0  0 15  0  0  0  0  0  0  0  0  0 

In [100]:
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

       apple       0.57      0.17      0.27        23
      banana       0.81      1.00      0.89        21
   blackgram       0.38      0.50      0.43        20
    chickpea       1.00      1.00      1.00        26
     coconut       0.36      0.19      0.24        27
      coffee       0.94      0.94      0.94        17
      cotton       0.77      1.00      0.87        17
      grapes       0.37      0.79      0.50        14
        jute       0.42      0.35      0.38        23
 kidneybeans       0.38      0.25      0.30        20
      lentil       0.25      0.55      0.34        11
       maize       0.94      0.71      0.81        21
       mango       0.43      0.63      0.51        19
   mothbeans       0.29      0.08      0.13        24
    mungbean       0.37      0.53      0.43        19
   muskmelon       0.50      0.76      0.60        17
      orange       0.93      1.00      0.97        14
      papaya       0.85    

# Train a SVM model, make predictions and evaluate the model

- Accuracy, f1-score, precision, recall, confusion matrix, and classification report.

In [101]:
from sklearn.svm import SVC

In [102]:
model = SVC(kernel='linear' ,C=100)
model.fit(x_train, y_train)

/Users/abdullah/anaconda3/envs/Data_Analysis/lib/python3.11/site-packages/sklearn/utils/validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=100, kernel='linear')

In [103]:
y_pred = model.predict(x_test)

In [104]:
acc = accuracy_score(y_test, y_pred)
print('accuracy_score is : ', acc)

f1 = f1_score(y_test, y_pred, average='weighted')
print('f1_score is : ', f1)

prec = precision_score(y_test, y_pred, average='weighted')
print('precision_score is : ', prec)

recall = recall_score(y_test, y_pred, average='weighted')
print('recall_score is : ', recall)

cm = confusion_matrix(y_test, y_pred)
print('confusion_matrix is : ', cm)

accuracy_score is :  0.6954545454545454
f1_score is :  0.6799267936410356
precision_score is :  0.7068635973984293
recall_score is :  0.6954545454545454
confusion_matrix is :  [[ 2  0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0  0  0  7  0  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 19  0  0  0  0  0  0  0  7  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0 16  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0 12  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  3  0  0 13  0  0  0  0  0  0  0  0  0  0  0  7  0]
 [ 0  0  0  0  0  0  0  0  0 14  0  0  0  1  0  0  0  0  5  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0  6  0  0  0  0  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0  0 20  0  0  0  0  0  0  0  0  0 

In [105]:
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

       apple       0.50      0.09      0.15        23
      banana       1.00      1.00      1.00        21
   blackgram       0.67      0.60      0.63        20
    chickpea       1.00      1.00      1.00        26
     coconut       0.83      0.70      0.76        27
      coffee       0.84      0.94      0.89        17
      cotton       0.89      1.00      0.94        17
      grapes       0.36      0.86      0.51        14
        jute       0.48      0.57      0.52        23
 kidneybeans       0.44      0.70      0.54        20
      lentil       0.32      0.55      0.40        11
       maize       1.00      0.95      0.98        21
       mango       0.61      0.74      0.67        19
   mothbeans       0.83      0.42      0.56        24
    mungbean       0.59      0.84      0.70        19
   muskmelon       0.60      0.71      0.65        17
      orange       1.00      1.00      1.00        14
      papaya       1.00    

# Train a Decision tree model, make predictions and evaluate the model

- Accuracy, f1-score, precision, recall, confusion matrix, and classification report.

In [106]:
from sklearn.tree import DecisionTreeClassifier

In [107]:
DTC = DecisionTreeClassifier()
DTC.fit(x_train, y_train)

DecisionTreeClassifier()

In [108]:
y_pred = model.predict(x_test)

In [109]:
acc = accuracy_score(y_test, y_pred)
print('accuracy_score is : ', acc)

f1 = f1_score(y_test, y_pred, average='weighted')
print('f1_score is : ', f1)

prec = precision_score(y_test, y_pred, average='weighted')
print('precision_score is : ', prec)

recall = recall_score(y_test, y_pred, average='weighted')
print('recall_score is : ', recall)

cm = confusion_matrix(y_test, y_pred)
print('confusion_matrix is : ', cm)

accuracy_score is :  0.6954545454545454
f1_score is :  0.6799267936410356
precision_score is :  0.7068635973984293
recall_score is :  0.6954545454545454
confusion_matrix is :  [[ 2  0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0  0  0  7  0  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 19  0  0  0  0  0  0  0  7  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0 16  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0 12  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  3  0  0 13  0  0  0  0  0  0  0  0  0  0  0  7  0]
 [ 0  0  0  0  0  0  0  0  0 14  0  0  0  1  0  0  0  0  5  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0  6  0  0  0  0  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0  0 20  0  0  0  0  0  0  0  0  0 

In [110]:
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

       apple       0.50      0.09      0.15        23
      banana       1.00      1.00      1.00        21
   blackgram       0.67      0.60      0.63        20
    chickpea       1.00      1.00      1.00        26
     coconut       0.83      0.70      0.76        27
      coffee       0.84      0.94      0.89        17
      cotton       0.89      1.00      0.94        17
      grapes       0.36      0.86      0.51        14
        jute       0.48      0.57      0.52        23
 kidneybeans       0.44      0.70      0.54        20
      lentil       0.32      0.55      0.40        11
       maize       1.00      0.95      0.98        21
       mango       0.61      0.74      0.67        19
   mothbeans       0.83      0.42      0.56        24
    mungbean       0.59      0.84      0.70        19
   muskmelon       0.60      0.71      0.65        17
      orange       1.00      1.00      1.00        14
      papaya       1.00    

# Train a Decision tree model, make predictions and evaluate the model

- Accuracy, f1-score, precision, recall, confusion matrix, and classification report.

In [111]:
from sklearn.ensemble import RandomForestClassifier

In [112]:
RFC = RandomForestClassifier()
RFC.fit(x_train, y_train)

/Users/abdullah/anaconda3/envs/Data_Analysis/lib/python3.11/site-packages/sklearn/base.py:1152: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier()

In [113]:
y_pred = model.predict(x_test)

In [114]:
acc = accuracy_score(y_test, y_pred)
print('accuracy_score is : ', acc)

f1 = f1_score(y_test, y_pred, average='weighted')
print('f1_score is : ', f1)

prec = precision_score(y_test, y_pred, average='weighted')
print('precision_score is : ', prec)

recall = recall_score(y_test, y_pred, average='weighted')
print('recall_score is : ', recall)

cm = confusion_matrix(y_test, y_pred)
print('confusion_matrix is : ', cm)

accuracy_score is :  0.6954545454545454
f1_score is :  0.6799267936410356
precision_score is :  0.7068635973984293
recall_score is :  0.6954545454545454
confusion_matrix is :  [[ 2  0  0  0  0  0  0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0  0  0  7  0  0  1  0  0  0  0  0  0  0  0]
 [ 0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 19  0  0  0  0  0  0  0  7  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0 16  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0 12  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  3  0  0 13  0  0  0  0  0  0  0  0  0  0  0  7  0]
 [ 0  0  0  0  0  0  0  0  0 14  0  0  0  1  0  0  0  0  5  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0  6  0  0  0  0  0  0  0  2  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0  0 20  0  0  0  0  0  0  0  0  0 

In [115]:
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

       apple       0.50      0.09      0.15        23
      banana       1.00      1.00      1.00        21
   blackgram       0.67      0.60      0.63        20
    chickpea       1.00      1.00      1.00        26
     coconut       0.83      0.70      0.76        27
      coffee       0.84      0.94      0.89        17
      cotton       0.89      1.00      0.94        17
      grapes       0.36      0.86      0.51        14
        jute       0.48      0.57      0.52        23
 kidneybeans       0.44      0.70      0.54        20
      lentil       0.32      0.55      0.40        11
       maize       1.00      0.95      0.98        21
       mango       0.61      0.74      0.67        19
   mothbeans       0.83      0.42      0.56        24
    mungbean       0.59      0.84      0.70        19
   muskmelon       0.60      0.71      0.65        17
      orange       1.00      1.00      1.00        14
      papaya       1.00    

# Train a default KNN model, make predictions and evaluate the model

- Accuracy, f1-score, precision, recall, confusion matrix, and classification report.

In [117]:
from sklearn.neighbors import KNeighborsClassifier

In [118]:
KNN = KNeighborsClassifier()
KNN.fit(x_train,y_train)

/Users/abdullah/anaconda3/envs/Data_Analysis/lib/python3.11/site-packages/sklearn/neighbors/_classification.py:233: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [119]:
y_pred = KNN.predict(x_test)

In [120]:
acc = accuracy_score(y_test, y_pred)
print('accuracy_score is : ', acc)

f1 = f1_score(y_test, y_pred, average='weighted')
print('f1_score is : ', f1)

prec = precision_score(y_test, y_pred, average='weighted')
print('precision_score is : ', prec)

recall = recall_score(y_test, y_pred, average='weighted')
print('recall_score is : ', recall)

cm = confusion_matrix(y_test, y_pred)
print('confusion_matrix is : ', cm)

accuracy_score is :  0.6386363636363637
f1_score is :  0.6419389105531391
precision_score is :  0.6641197651033177
recall_score is :  0.6386363636363637
confusion_matrix is :  [[10  0  0  0  0  0  0 13  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 13  0  0  0  0  0  0  3  4  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 19  0  0  0  0  0  0  0  8  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 15  1  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 15  0  0  0  0  2  0  0  0  0  0  0  0  0  0  0]
 [ 6  0  0  0  0  0  0  8  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  0  0 12  0  0  0  0  0  0  0  0  0  0  0  9  0]
 [ 0  0  3  0  0  0  0  0  0  5  6  0  0  3  1  0  0  0  2  0  0  0]
 [ 0  0  2  0  0  0  0  0  0  3  4  0  0  0  0  0  0  0  2  0  0  0]
 [ 0  0  1  0  0  0  3  0  0  0  0 17  0  0  0  0  0  0  0  0  0 

In [121]:
print(classification_report(y_test , y_pred))

              precision    recall  f1-score   support

       apple       0.62      0.43      0.51        23
      banana       1.00      1.00      1.00        21
   blackgram       0.62      0.65      0.63        20
    chickpea       1.00      1.00      1.00        26
     coconut       0.79      0.70      0.75        27
      coffee       0.83      0.88      0.86        17
      cotton       0.79      0.88      0.83        17
      grapes       0.38      0.57      0.46        14
        jute       0.52      0.52      0.52        23
 kidneybeans       0.25      0.25      0.25        20
      lentil       0.16      0.36      0.22        11
       maize       0.89      0.81      0.85        21
       mango       0.56      0.79      0.65        19
   mothbeans       0.40      0.25      0.31        24
    mungbean       0.27      0.37      0.31        19
   muskmelon       0.56      0.53      0.55        17
      orange       1.00      1.00      1.00        14
      papaya       1.00    

# Try different values of K in the KNN model and select the best one.

- Based on the accuracy.

In [130]:
x = 0
for i in range(1, 40):
    KNN = KNeighborsClassifier(n_neighbors=i)
    KNN.fit(x_train,y_train)
    y_pred = KNN.predict(x_test)
    if accuracy_score(y_test, y_pred) > x:
        x = accuracy_score(y_test, y_pred)
        k = i

print('accuracy_score is : ', x)
print('Best Sample is : ',k)


/Users/abdullah/anaconda3/envs/Data_Analysis/lib/python3.11/site-packages/sklearn/neighbors/_classification.py:233: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/Users/abdullah/anaconda3/envs/Data_Analysis/lib/python3.11/site-packages/sklearn/neighbors/_classification.py:233: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/Users/abdullah/anaconda3/envs/Data_Analysis/lib/python3.11/site-packages/sklearn/neighbors/_classification.py:233: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/Users/abdullah/anaconda3/envs/Data_Analysis/lib/python3.11/site-packages/sklearn/neighbors/_classification.py:2

accuracy_score is :  0.675
Best Sample is :  9


/Users/abdullah/anaconda3/envs/Data_Analysis/lib/python3.11/site-packages/sklearn/neighbors/_classification.py:233: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/Users/abdullah/anaconda3/envs/Data_Analysis/lib/python3.11/site-packages/sklearn/neighbors/_classification.py:233: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/Users/abdullah/anaconda3/envs/Data_Analysis/lib/python3.11/site-packages/sklearn/neighbors/_classification.py:233: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/Users/abdullah/anaconda3/envs/Data_Analysis/lib/python3.11/site-packages/sklearn/neighbors/_classification.py:2