# Sowing Success: How Machine Learning Helps Farmers Select the Best Crops

Measuring essential soil metrics such as nitrogen, phosphorous, potassium levels, and pH value is an important aspect of assessing soil condition. However, it can be an expensive and time-consuming process, which can cause farmers to prioritize which metrics to measure based on their budget constraints.

Farmers have various options when it comes to deciding which crop to plant each season. Their primary objective is to maximize the yield of their crops, taking into account different factors. One crucial factor that affects crop growth is the condition of the soil in the field, which can be assessed by measuring basic elements such as nitrogen and potassium levels. Each crop has an ideal soil condition that ensures optimal growth and maximum yield.

A farmer reached out to you as a machine learning expert for assistance in selecting the best crop for his field. They've provided you with a dataset called `soil_measures.csv`, which contains:

- `"N"`: Nitrogen content ratio in the soil
- `"P"`: Phosphorous content ratio in the soil
- `"K"`: Potassium content ratio in the soil
- `"pH"` value of the soil
- `"crop"`: categorical values that contain various crops (target variable).

Each row in this dataset represents various measures of the soil in a particular field. Based on these measurements, the crop specified in the `"crop"` column is the optimal choice for that field.  

In this project, you will apply machine learning to build a multi-class classification model to predict the type of `"crop"`, while using techniques to avoid multicollinearity, which is a concept where two or more features are highly correlated.

# Import Libraries

In [19]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline


# Load the Dataset and make EDA

- Print the head, tail, describe, info, shape.

In [20]:
df = pd.read_csv('soil_measures.csv')
df.head()


N   P   K        ph  crop
0  90  42  43  6.502985  rice
1  85  58  41  7.038096  rice
2  60  55  44  7.840207  rice
3  74  35  40  6.980401  rice
4  78  42  42  7.628473  rice

In [21]:
df.tail()


N   P   K        ph    crop
2195  107  34  32  6.780064  coffee
2196   99  15  27  6.086922  coffee
2197  118  33  30  6.362608  coffee
2198  117  32  34  6.758793  coffee
2199  104  18  30  6.779833  coffee

In [22]:
df.describe()


N            P            K           ph
count  2200.000000  2200.000000  2200.000000  2200.000000
mean     50.551818    53.362727    48.149091     6.469480
std      36.917334    32.985883    50.647931     0.773938
min       0.000000     5.000000     5.000000     3.504752
25%      21.000000    28.000000    20.000000     5.971693
50%      37.000000    51.000000    32.000000     6.425045
75%      84.250000    68.000000    49.000000     6.923643
max     140.000000   145.000000   205.000000     9.935091

In [23]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   N       2200 non-null   int64  
 1   P       2200 non-null   int64  
 2   K       2200 non-null   int64  
 3   ph      2200 non-null   float64
 4   crop    2200 non-null   object 
dtypes: float64(1), int64(3), object(1)
memory usage: 86.1+ KB


In [24]:
df.shape

(2200, 5)

# Check the number of classes in the target label

In [25]:
df['crop'].value_counts().count()

22

# Check is there missing data

In [26]:
df.isna().sum().sum()

0

# Train test split

- Test size is 20%

In [27]:
# Encoding
from sklearn import preprocessing 
label_encoder = preprocessing.LabelEncoder() 
df['crop']= label_encoder.fit_transform(df['crop'])

In [28]:
from sklearn.model_selection import train_test_split
X = df.drop('crop',axis=1)
Y = df['crop']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)


# Train a multiclass logistic regression model, make predictions and evaluate the model

- Accuracy, f1-score, precision, recall, confusion matrix, and classification report.

In [29]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, f1_score, precision_score, recall_score

log_modle = LogisticRegression()
log_modle.fit(X_train,Y_train)
Y_pred = log_modle.predict(X_test)

print(accuracy_score(Y_test,Y_pred))

print(f1_score(Y_test,Y_pred,average='micro'))

print(precision_score(Y_test,Y_pred,average="micro"))

print(recall_score(Y_test,Y_pred, average="micro"))

print(confusion_matrix(Y_test,Y_pred))

print(classification_report(Y_test,Y_pred))



0.5681818181818182
0.5681818181818182
0.5681818181818182
0.5681818181818182
[[ 4  0  0  0  0  0  0 19  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 10  0  0  0  0  0  0  1  7  0  0  1  1  0  0  0  0  0  0  0]
 [ 0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0  0  0 10  0  0  0  0  0  0 11  0  1]
 [ 0  0  0  0  0 16  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 3  0  0  0  0  0  0 11  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  1  0  0  8  0  0  0  0  0  0  0  0  2  0  0 10  0]
 [ 0  0  3  0  0  0  0  0  0  5  4  0  0  0  1  0  0  0  7  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  1  6  0  0  1  1  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  5  0  1  0  0 15  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  3  0  0  0  1  0  0  0 12  1  0  0  0  1  0  1  0  0]
 [ 0  1  3  0  0  0  0  0  

# Train a SVM model, make predictions and evaluate the model

- Accuracy, f1-score, precision, recall, confusion matrix, and classification report.

In [30]:
from sklearn.svm import SVC
svm = SVC(kernel = 'rbf',random_state=42) 
svm.fit(X_train, Y_train)

Y_pred = svm.predict(X_test)

print(accuracy_score(Y_test,Y_pred))

print(f1_score(Y_test,Y_pred,average='micro'))

print(precision_score(Y_test,Y_pred,average="micro"))

print(recall_score(Y_test,Y_pred, average="micro"))

print(confusion_matrix(Y_test,Y_pred))

print(classification_report(Y_test,Y_pred))



0.6045454545454545
0.6045454545454545
0.6045454545454545
0.6045454545454545
[[ 1  0  0  0  0  0  0 22  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 11  0  0  0  0  0  0  0  9  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 18  0  0  0  0  0  0  0  8  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0 15  1  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 14  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0 22  0]
 [ 0  0  3  0  0  0  0  0  0  0 16  0  0  0  1  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  1  9  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  4  0  0  0  0 16  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0  0  0 13  0  1  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  

# Train a Decision tree model, make predictions and evaluate the model

- Accuracy, f1-score, precision, recall, confusion matrix, and classification report.

In [31]:
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(criterion=  'entropy',random_state=42) 
tree.fit(X_train, Y_train)

Y_pred = tree.predict(X_test)

print(accuracy_score(Y_test,Y_pred))

print(f1_score(Y_test,Y_pred,average='micro'))

print(precision_score(Y_test,Y_pred,average="micro"))

print(recall_score(Y_test,Y_pred, average="micro"))

print(confusion_matrix(Y_test,Y_pred))

print(classification_report(Y_test,Y_pred))



0.7636363636363637
0.7636363636363637
0.7636363636363637
0.7636363636363637
[[13  0  0  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 17  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 24  0  0  0  0  0  0  0  2  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0 16  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 8  0  0  0  0  0  0  6  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  0  0 11  0  0  0  0  0  0  0  0  0  0  0 10  0]
 [ 0  0  0  0  0  0  0  0  0 14  1  0  0  1  0  0  0  0  4  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  1  5  0  0  0  0  0  0  0  4  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  3  0  0  0  0  0  0  0 15  0  0  0  0  0  0  1  0  0]
 [ 0  0  1  0  0  0  0  0  

# Train a Decision tree model, make predictions and evaluate the model

- Accuracy, f1-score, precision, recall, confusion matrix, and classification report.

In [32]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(criterion=  'entropy',random_state=42) 
RF.fit(X_train, Y_train)

Y_pred = RF.predict(X_test)

print(accuracy_score(Y_test,Y_pred))

print(f1_score(Y_test,Y_pred,average='micro'))

print(precision_score(Y_test,Y_pred,average="micro"))

print(recall_score(Y_test,Y_pred, average="micro"))

print(confusion_matrix(Y_test,Y_pred))

print(classification_report(Y_test,Y_pred))



0.8090909090909091
0.8090909090909091
0.8090909090909091
0.8090909090909091
[[14  0  0  0  0  0  0  9  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 17  0  0  0  0  0  0  0  2  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 24  0  0  0  0  0  0  0  3  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 16  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 17  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 7  0  0  0  0  0  0  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  0  0 14  0  0  0  0  0  0  0  0  0  0  0  7  0]
 [ 0  0  0  0  0  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  1  8  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0  0 20  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  3  0  0  0  0  0  0  0 14  1  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  

# Train a default KNN model, make predictions and evaluate the model

- Accuracy, f1-score, precision, recall, confusion matrix, and classification report.

In [33]:
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(n_neighbors=1) 
KNN.fit(X_train, Y_train)

Y_pred = KNN.predict(X_test)

print(accuracy_score(Y_test,Y_pred))

print(f1_score(Y_test,Y_pred,average='micro'))

print(precision_score(Y_test,Y_pred,average="micro"))

print(recall_score(Y_test,Y_pred, average="micro"))

print(confusion_matrix(Y_test,Y_pred))

print(classification_report(Y_test,Y_pred))



0.634090909090909
0.634090909090909
0.634090909090909
0.634090909090909
[[ 9  0  0  0  0  0  0 14  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 21  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 12  0  0  0  0  0  0  3  4  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  0  0 26  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 18  0  0  0  0  0  0  0  8  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0 15  1  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0 16  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0]
 [ 7  0  0  0  0  0  0  7  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  2  0  0 15  0  0  0  0  0  0  0  0  0  0  0  6  0]
 [ 0  0  4  0  0  0  0  0  0  3  7  0  0  2  1  0  0  0  3  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  2  3  0  0  0  1  0  0  0  4  0  0  0]
 [ 0  0  0  0  0  0  2  0  0  0  0 19  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  8  0  0  0  0  0  0  0 10  0  1  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0

# Try different values of K in the KNN model and select the best one.

- Based on the accuracy.

In [34]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

knn = KNeighborsClassifier()

param_grid = dict(n_neighbors = list(range(1,20)))

grid = GridSearchCV(knn, param_grid, cv = 5, scoring = 'accuracy')
grid.fit(X_train,Y_train)

print (grid.best_score_)
print (grid.best_params_)
print (grid.best_estimator_)



0.65625
{'n_neighbors': 4}
KNeighborsClassifier(n_neighbors=4)
